import { createStore } from 'vuex';

export default createStore({
  state: {
    cards: [
      {
        id: '1',
        job: 'Front End (Angular) Developer',
        image: 'office',
        logo: 'newmedia',
        status: 'Горячая🔥',
        salary: '1000$',
        company: 'NewGMedia',
        city: 'Киев',
        time: '37 минут назад',
        advantages: [
          'Paid Vacation',
          'Sick leaves',
          'English classes',
          'Удобный офис',
          'Гибкий график',
          'Интересные проекты ',
          'Зеленый офис',
          'Помощь менторов',
          'Бесплатное обучение',
        ],
      },
      {
        id: '2',
        job: 'Junior Magento Front-end developer',
        image: 'office2',
        logo: 'konsolstudio',
        status: 'Новая🌿',
        salary: '2000$',
        company: 'Konsol Studio',
        city: 'Львов',
        time: '1 день назад',
        advantages: [
          'Paid Vacation',
          'Sick leaves',
          'English classes',
          'Удобный офис',
          'Гибкий график',
          'Интересные проекты ',
          'Зеленый офис',
          'Помощь менторов',
          'Бесплатное обучение',
        ],
      },
      {
        id: '3',
        job: 'Front End Developer (Angular)',
        image: 'office3',
        logo: 'neonomics',
        status: 'Горячая🔥',
        salary: '1200$',
        company: 'Neonomics Ukraine',
        city: 'Одесса',
        time: '37 минут назад',
        advantages: [
          'Paid Vacation',
          'Sick leaves',
          'English classes',
          'Удобный офис',
          'Гибкий график',
          'Интересные проекты ',
          'Зеленый офис',
          'Помощь менторов',
          'Бесплатное обучение',
        ],
      },
      {
        id: '4',
        job: 'Junior Front-End developer, Angular/ React',
        image: 'office4',
        logo: 'iteam',
        status: 'Новая🌿',
        salary: '800-1100$',
        company: 'ITeam Company',
        city: 'Киев',
        time: '1 день назад',
        advantages: [
          'Paid Vacation',
          'Sick leaves',
          'English classes',
          'Удобный офис',
          'Гибкий график',
          'Интересные проекты ',
          'Зеленый офис',
          'Помощь менторов',
          'Бесплатное обучение',
        ],
      },
      {
        id: '5',
        job: 'Junior Frontend Engineer',
        image: 'office',
        logo: 'codeinn',
        status: 'Новая🌿',
        salary: '1100$',
        company: 'CodedInn',
        city: 'Киев',
        time: '1 день назад',
        advantages: [
          'Paid Vacation',
          'Sick leaves',
          'English classes',
          'Удобный офис',
          'Гибкий график',
          'Интересные проекты ',
          'Зеленый офис',
          'Помощь менторов',
          'Бесплатное обучение',
        ],
      },
      {
        id: '6',
        job: 'Junior Front-end developer (ReactJS)',
        image: 'office2',
        logo: 'smartorange',
        status: 'Горячая🔥',
        salary: '900$',
        company: 'SmartOrange',
        city: 'Киев',
        time: '37 минут назад',
        advantages: [
          'Paid Vacation',
          'Sick leaves',
          'English classes',
          'Удобный офис',
          'Гибкий график',
          'Интересные проекты ',
          'Зеленый офис',
          'Помощь менторов',
          'Бесплатное обучение',
        ],
      },
      {
        id: '7',
        job: 'Middle Front-End Developer (Angular 2+)',
        image: 'office3',
        logo: 'sendpulse',
        status: 'Новая🌿',
        salary: '1500$',
        company: 'SendPulse',
        city: 'Днепр',
        time: '1 день назад',
        advantages: [
          'Paid Vacation',
          'Sick leaves',
          'English classes',
          'Удобный офис',
          'Гибкий график',
          'Интересные проекты ',
          'Зеленый офис',
          'Помощь менторов',
          'Бесплатное обучение',
        ],
      },
      {
        id: '8',
        job: 'Front-end Developer',
        image: 'office4',
        logo: 'futurra',
        status: 'Горячая🔥',
        salary: '1000$',
        company: 'Futurra Group',
        city: 'Киев',
        time: '37 минут назад',
        advantages: [
          'Paid Vacation',
          'Sick leaves',
          'English classes',
          'Удобный офис',
          'Гибкий график',
          'Интересные проекты ',
          'Зеленый офис',
          'Помощь менторов',
          'Бесплатное обучение',
        ],
      },
      {
        id: '9',
        job: 'Front-end developer (Верстальщик)',
        image: 'office',
        logo: 'brab',
        status: 'Новая🌿',
        salary: '1000$',
        company: 'BRAB',
        city: 'Днепр',
        time: '1 день назад',
        advantages: [
          'Paid Vacation',
          'Sick leaves',
          'English classes',
          'Удобный офис',
          'Гибкий график',
          'Интересные проекты ',
          'Зеленый офис',
          'Помощь менторов',
          'Бесплатное обучение',
        ],
      },
      {
        id: '10',
        job: 'JavaScript/React Developer ',
        image: 'office2',
        logo: 'uran',
        status: 'Новая🌿',
        salary: '1300$',
        company: 'Uran Company',
        city: 'Запорожье',
        time: '1 день назад',
        advantages: [
          'Paid Vacation',
          'Sick leaves',
          'English classes',
          'Удобный офис',
          'Гибкий график',
          'Интересные проекты ',
          'Зеленый офис',
          'Помощь менторов',
          'Бесплатное обучение',
        ],
      },
    ],
    skills:[
      {
        technology:'Programming Languages',
        programs:['HTML','CSS','JS','TS'], 
      },
      {
        technology:'Preprocessors',
        programs:['SCSS'], 
      },
      {
        technology:'CSSFrameworks',
        programs:['Bootstrap','Tailwind','WindiCSS'], 
      },
      {
        technology:'JSFrameworks',
        programs:['Vue'], 
      },
      {
        technology:'Bundlers',
        programs:['Webpack','Gulp','Vite'], 
      },
      {
        technology:'Design Tools',
        programs:['Figma','Photoshop'], 
      },
      {
        technology:'Foreign Languages',
        programs:['English','Polish','Spanish'], 
      },
    ]
  },
  mutations: {},
  actions: {},
  modules: {},
});
